version: '2'
services:
    testclem-app:
        image: testclem
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://testclem-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=testClem
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    testclem-mongodb:
        extends:
            file: mongodb.yml
            service: testclem-mongodb
